domain="vidyapatne421gmail.onmicrosoft.com"
# user_principal_name = "nikhil"
# display_name = "Nikhil"
# user_profile = "developer"
# company_name = "GS Lab"
# job_title = "Software Engineer"
# department = "IDM"
# mobile = "8605358076"
